source:       .
destination:  ./_site
markdown:     kramdown
# kramdown:
#   parse_block_html: true # allow markdown in <div> etc.
permalink:    date
# safe:         true
markdown_ext: md

# testing for redirect-from
baseurl: "/docs"

gems:
  - jekyll-redirect-from

collections:
#
# Universal
#
  u-pos:
    output: true
    permalink: /u/pos/:path.html
  u-feat:
    output: true
    permalink: /u/feat/:path.html
  u-dep:
    output: true
    permalink: /u/dep/:path.html
  u-overview:
    output: true
  ext-feat:
    output: true
    permalink: /u/ext-feat/:path.html
#
# English
#
  en-pos:
    output: true
    permalink: /en/pos/:path.html
  en-feat:
    output: true
    permalink: /en/feat/:path.html
  en-dep:
    output: true
    permalink: /en/dep/:path.html
  en-overview:
    output: true
#
# Finnish
#
  fi-pos:
    output: true
    permalink: /fi/pos/:path.html
  fi-feat:
    output: true
    permalink: /fi/feat/:path.html
  fi-dep:
    output: true
    permalink: /fi/dep/:path.html
  fi-overview:
    output: true
#
# Swedish
#
  sv-pos:
    output: true
    permalink: /sv/pos/:path.html
  sv-feat:
    output: true
    permalink: /sv/feat/:path.html
  sv-dep:
    output: true
    permalink: /sv/dep/:path.html
  sv-overview:
    output: true
#
# Hungarian
#
  hu-pos:
    output: true
    permalink: /hu/pos/:path.html
  hu-feat:
    output: true
    permalink: /hu/feat/:path.html
  hu-dep:
    output: true
    permalink: /hu/dep/:path.html
  hu-overview:
    output: true
#
# Irish
#
  ga-pos:
    output: true
    permalink: /ga/pos/:path.html
  ga-feat:
    output: true
    permalink: /ga/feat/:path.html
  ga-dep:
    output: true
    permalink: /ga/dep/:path.html
  ga-overview:
    output: true
#
# Bulgarian
#
  bg-pos:
    output: true
    permalink: /bg/pos/:path.html
  bg-feat:
    output: true
    permalink: /bg/feat/:path.html
  bg-dep:
    output: true
    permalink: /bg/dep/:path.html
  bg-overview:
    output: true
#
# Persian
#
  fa-pos:
    output: true
    permalink: /fa/pos/:path.html
  fa-feat:
    output: true
    permalink: /fa/feat/:path.html
  fa-dep:
    output: true
    permalink: /fa/dep/:path.html
  fa-overview:
    output: true
#
# Czech
#
  cs-pos:
    output: true
    permalink: /cs/pos/:path.html
  cs-feat:
    output: true
    permalink: /cs/feat/:path.html
  cs-dep:
    output: true
    permalink: /cs/dep/:path.html
  cs-overview:
    output: true
#
# Hebrew
#
  he-pos:
    output: true
    permalink: /he/pos/:path.html
  he-feat:
    output: true
    permalink: /he/feat/:path.html
  he-dep:
    output: true
    permalink: /he/dep/:path.html
  he-overview:
    output: true
#
# Spanish
#
  es-pos:
    output: true
    permalink: /es/pos/:path.html
  es-feat:
    output: true
    permalink: /es/feat/:path.html
  es-dep:
    output: true
    permalink: /es/dep/:path.html
  es-overview:
    output: true
#
# French
#
  fr-pos:
    output: true
    permalink: /fr/pos/:path.html
  fr-feat:
    output: true
    permalink: /fr/feat/:path.html
  fr-dep:
    output: true
    permalink: /fr/dep/:path.html
  fr-overview:
    output: true
#
# German
#
  de-pos:
    output: true
    permalink: /de/pos/:path.html
  de-feat:
    output: true
    permalink: /de/feat/:path.html
  de-dep:
    output: true
    permalink: /de/dep/:path.html
  de-overview:
    output: true
#
# Greek
#
  el-pos:
    output: true
    permalink: /el/pos/:path.html
  el-feat:
    output: true
    permalink: /el/feat/:path.html
  el-dep:
    output: true
    permalink: /el/dep/:path.html
  el-overview:
    output: true
#
# Basque
#
  eu-pos:
    output: true
    permalink: /eu/pos/:path.html
  eu-feat:
    output: true
    permalink: /eu/feat/:path.html
  eu-dep:
    output: true
    permalink: /eu/dep/:path.html
  eu-overview:
    output: true
#
# Italian
#
  it-pos:
    output: true
    permalink: /it/pos/:path.html
  it-feat:
    output: true
    permalink: /it/feat/:path.html
  it-dep:
    output: true
    permalink: /it/dep/:path.html
  it-overview:
    output: true
#
# Korean
#
  ko-pos:
    output: true
    permalink: /ko/pos/:path.html
  ko-feat:
    output: true
    permalink: /ko/feat/:path.html
  ko-dep:
    output: true
    permalink: /ko/dep/:path.html
  ko-overview:
    output: true
#
# Japanese
#
  ja-pos:
    output: true
    permalink: /ja/pos/:path.html
  ja-feat:
    output: true
    permalink: /ja/feat/:path.html
  ja-dep:
    output: true
    permalink: /ja/dep/:path.html
  ja-overview:
    output: true
#
# Template
#
  template-pos:
    output: true
    permalink: /template/pos/:path.html
  template-feat:
    output: true
    permalink: /template/feat/:path.html
  template-dep:
    output: true
    permalink: /template/dep/:path.html
  template-overview:
    output: true
#
# Tagset conversion tables (even for languages that do not have their sections yet)
#
  tagset-conversion:
    output: true
    permalink: /tagset-conversion/:path.html

excerpt_separator: "\n\n"

# URL configuration

home: "http://universaldependencies.github.io/docs/"
tracker: "https://github.com/universaldependencies/docs/issues"
git_raw: "https://raw.githubusercontent.com/universaldependencies/docs/pages-source"
git_edit: "https://github.com/universaldependencies/docs/edit/pages-source"
