source:       .
destination:  ./_site
markdown:     kramdown
# don't change the following; coderay will break the embedded
# annotations.
kramdown:
  enable_coderay: false
#   parse_block_html: true # allow markdown in <div> etc.
permalink:    date
# safe:         true
markdown_ext: md

# testing for redirect-from
baseurl: "/docs"

gems:
  - jekyll-redirect-from

collections:
#
# Universal
#
  u-pos:
    output: true
    permalink: /u/pos/:path.html
  u-feat:
    output: true
    permalink: /u/feat/:path.html
  u-dep:
    output: true
    permalink: /u/dep/:path.html
  u-overview:
    output: true
  ext-feat:
    output: true
    permalink: /u/ext-feat/:path.html
#
# English
#
  en-pos:
    output: true
    permalink: /en/pos/:path.html
  en-feat:
    output: true
    permalink: /en/feat/:path.html
  en-dep:
    output: true
    permalink: /en/dep/:path.html
  en-overview:
    output: true
#
# Finnish
#
  fi-pos:
    output: true
    permalink: /fi/pos/:path.html
  fi-feat:
    output: true
    permalink: /fi/feat/:path.html
  fi-dep:
    output: true
    permalink: /fi/dep/:path.html
  fi-overview:
    output: true
#
# Swedish
#
  sv-pos:
    output: true
    permalink: /sv/pos/:path.html
  sv-feat:
    output: true
    permalink: /sv/feat/:path.html
  sv-dep:
    output: true
    permalink: /sv/dep/:path.html
  sv-overview:
    output: true
#
# Hungarian
#
  hu-pos:
    output: true
    permalink: /hu/pos/:path.html
  hu-feat:
    output: true
    permalink: /hu/feat/:path.html
  hu-dep:
    output: true
    permalink: /hu/dep/:path.html
  hu-overview:
    output: true
#
# Irish
#
  ga-pos:
    output: true
    permalink: /ga/pos/:path.html
  ga-feat:
    output: true
    permalink: /ga/feat/:path.html
  ga-dep:
    output: true
    permalink: /ga/dep/:path.html
  ga-overview:
    output: true
#
# Bulgarian
#
  bg-pos:
    output: true
    permalink: /bg/pos/:path.html
  bg-feat:
    output: true
    permalink: /bg/feat/:path.html
  bg-dep:
    output: true
    permalink: /bg/dep/:path.html
  bg-overview:
    output: true
#
# Persian
#
  fa-pos:
    output: true
    permalink: /fa/pos/:path.html
  fa-feat:
    output: true
    permalink: /fa/feat/:path.html
  fa-dep:
    output: true
    permalink: /fa/dep/:path.html
  fa-overview:
    output: true
#
# Czech
#
  cs-pos:
    output: true
    permalink: /cs/pos/:path.html
  cs-feat:
    output: true
    permalink: /cs/feat/:path.html
  cs-dep:
    output: true
    permalink: /cs/dep/:path.html
  cs-overview:
    output: true
#
# Hebrew
#
  he-pos:
    output: true
    permalink: /he/pos/:path.html
  he-feat:
    output: true
    permalink: /he/feat/:path.html
  he-dep:
    output: true
    permalink: /he/dep/:path.html
  he-overview:
    output: true
#
# Spanish
#
  es-pos:
    output: true
    permalink: /es/pos/:path.html
  es-feat:
    output: true
    permalink: /es/feat/:path.html
  es-dep:
    output: true
    permalink: /es/dep/:path.html
  es-overview:
    output: true
#
# French
#
  fr-pos:
    output: true
    permalink: /fr/pos/:path.html
  fr-feat:
    output: true
    permalink: /fr/feat/:path.html
  fr-dep:
    output: true
    permalink: /fr/dep/:path.html
  fr-overview:
    output: true
#
# German
#
  de-pos:
    output: true
    permalink: /de/pos/:path.html
  de-feat:
    output: true
    permalink: /de/feat/:path.html
  de-dep:
    output: true
    permalink: /de/dep/:path.html
  de-overview:
    output: true
#
# Greek
#
  el-pos:
    output: true
    permalink: /el/pos/:path.html
  el-feat:
    output: true
    permalink: /el/feat/:path.html
  el-dep:
    output: true
    permalink: /el/dep/:path.html
  el-overview:
    output: true
#
# Basque
#
  eu-pos:
    output: true
    permalink: /eu/pos/:path.html
  eu-feat:
    output: true
    permalink: /eu/feat/:path.html
  eu-dep:
    output: true
    permalink: /eu/dep/:path.html
  eu-overview:
    output: true
#
# Italian
#
  it-pos:
    output: true
    permalink: /it/pos/:path.html
  it-feat:
    output: true
    permalink: /it/feat/:path.html
  it-dep:
    output: true
    permalink: /it/dep/:path.html
  it-overview:
    output: true
#
# Korean
#
  ko-pos:
    output: true
    permalink: /ko/pos/:path.html
  ko-feat:
    output: true
    permalink: /ko/feat/:path.html
  ko-dep:
    output: true
    permalink: /ko/dep/:path.html
  ko-overview:
    output: true
#
# Japanese
#
  ja-pos:
    output: true
    permalink: /ja/pos/:path.html
  ja-feat:
    output: true
    permalink: /ja/feat/:path.html
  ja-dep:
    output: true
    permalink: /ja/dep/:path.html
  ja-overview:
    output: true
#
# Chinese
#
  zh-pos:
    output: true
    permalink: /zh/pos/:path.html
  zh-feat:
    output: true
    permalink: /zh/feat/:path.html
  zh-dep:
    output: true
    permalink: /zh/dep/:path.html
  zh-overview:
    output: true
#
# Romanian
#
  ro-pos:
    output: true
    permalink: /ro/pos/:path.html
  ro-feat:
    output: true
    permalink: /ro/feat/:path.html
  ro-dep:
    output: true
    permalink: /ro/dep/:path.html
  ro-overview:
    output: true
#
# Slovenian
#
  sl-pos:
    output: true
    permalink: /sl/pos/:path.html
  sl-feat:
    output: true
    permalink: /sl/feat/:path.html
  sl-dep:
    output: true
    permalink: /sl/dep/:path.html
  sl-overview:
    output: true
#
# Danish
#
  da-pos:
    output: true
    permalink: /da/pos/:path.html
  da-feat:
    output: true
    permalink: /da/feat/:path.html
  da-dep:
    output: true
    permalink: /da/dep/:path.html
  da-overview:
    output: true
#
# Croatian
#
  hr-pos:
    output: true
    permalink: /hr/pos/:path.html
  hr-feat:
    output: true
    permalink: /hr/feat/:path.html
  hr-dep:
    output: true
    permalink: /hr/dep/:path.html
  hr-overview:
    output: true
#
# Indonesian
#
  id-pos:
    output: true
    permalink: /id/pos/:path.html
  id-feat:
    output: true
    permalink: /id/feat/:path.html
  id-dep:
    output: true
    permalink: /id/dep/:path.html
  id-overview:
    output: true
#
# Amharic
#
  am-pos:
    output: true
    permalink: /am/pos/:path.html
  am-feat:
    output: true
    permalink: /am/feat/:path.html
  am-dep:
    output: true
    permalink: /am/dep/:path.html
  am-overview:
    output: true
#
# Hindi
#
  hi-pos:
    output: true
    permalink: /hi/pos/:path.html
  hi-feat:
    output: true
    permalink: /hi/feat/:path.html
  hi-dep:
    output: true
    permalink: /hi/dep/:path.html
  hi-overview:
    output: true
#
# Ancient Greek
#
  grc-pos:
    output: true
    permalink: /grc/pos/:path.html
  grc-feat:
    output: true
    permalink: /grc/feat/:path.html
  grc-dep:
    output: true
    permalink: /grc/dep/:path.html
  grc-overview:
    output: true
#
# Latin
#
  la-pos:
    output: true
    permalink: /la/pos/:path.html
  la-feat:
    output: true
    permalink: /la/feat/:path.html
  la-dep:
    output: true
    permalink: /la/dep/:path.html
  la-overview:
    output: true
#
# Catalan
#
  ca-pos:
    output: true
    permalink: /ca/pos/:path.html
  ca-feat:
    output: true
    permalink: /ca/feat/:path.html
  ca-dep:
    output: true
    permalink: /ca/dep/:path.html
  ca-overview:
    output: true
#
# Template
#
  template-pos:
    output: true
    permalink: /template/pos/:path.html
  template-feat:
    output: true
    permalink: /template/feat/:path.html
  template-dep:
    output: true
    permalink: /template/dep/:path.html
  template-overview:
    output: true
#
# Tagset conversion tables (even for languages that do not have their sections yet)
#
  tagset-conversion:
    output: true
    permalink: /tagset-conversion/:path.html
#
# Meeting materials
#
  2015-08-23-uppsala:
    output: true
    permalink: /2015-08-23-uppsala/:path.html

excerpt_separator: "\n\n"

# URL configuration

home: "http://universaldependencies.github.io/docs/"
tracker: "https://github.com/universaldependencies/docs/issues"
git_raw: "https://raw.githubusercontent.com/universaldependencies/docs/pages-source"
git_edit: "https://github.com/universaldependencies/docs/edit/pages-source"
