source:       .
destination:  ./_site
markdown:     kramdown
# don't change the following; coderay will break the embedded
# annotations.
kramdown:
  enable_coderay: false
#   parse_block_html: true # allow markdown in <div> etc.
permalink:    date
# safe:         true
markdown_ext: md

baseurl: ""

plugins:
  - jekyll-redirect-from

liquid:
  error_mode: warn

collections:
#
# Universal
#
  u-pos:
    output: true
    permalink: /u/pos/:path.html
  u-feat:
    output: true
    permalink: /u/feat/:path.html
  u-dep:
    output: true
    permalink: /u/dep/:path.html
  u-overview:
    output: true
  ext-feat:
    output: true
    permalink: /u/ext-feat/:path.html
  cs:
    output: true
  en:
    output: true
  sv:
    output: true
  fi:
    output: true
  af:
    output: true
  ar:
    output: true
  be:
    output: true
  bg:
    output: true
  bm:
    output: true
  ca:
    output: true
  ckb:
    output: true
  cop:
    output: true
  cu:
    output: true
  da:
    output: true
  dar:
    output: true
  de:
    output: true
  el:
    output: true
  es:
    output: true
  et:
    output: true
  eu:
    output: true
  fa:
    output: true
  fo:
    output: true
  fr:
    output: true
  fro:
    output: true
  ga:
    output: true
  gl:
    output: true
  got:
    output: true
  grc:
    output: true
  he:
    output: true
  hsb:
    output: true
  hu:
    output: true
  hy:
    output: true
  it:
    output: true
  ja:
    output: true
  kk:
    output: true
  kmr:
    output: true
  ko:
    output: true
  ky:
    output: true
  la:
    output: true
  mr:
    output: true
  mt:
    output: true
  nl:
    output: true
  "no":
    output: true
  pcm:
    output: true
  pl:
    output: true
  pt:
    output: true
  ro:
    output: true
  ru:
    output: true
  sa:
    output: true
  sk:
    output: true
  sl:
    output: true
  sla:
    output: true
  swl:
    output: true
  ta:
    output: true
  tr:
    output: true
  uk:
    output: true
  urj:
    output: true
  vi:
    output: true
  yue:
    output: true
  zh:
    output: true
  myv:
    output: true
  ka:
    output: true
  yo:
    output: true
  br:
    output: true
  tl:
    output: true
  kpv:
    output: true
  pbv:
    output: true
  lv:
    output: true
  shp:
    output: true
  cy:
    output: true
  wbp:
    output: true
  wo:
    output: true
  akk:
    output: true
  sd:
    output: true
  bho:
    output: true
  qhe:
    output: true
  lt:
    output: true
  lzh:
    output: true
  aii:
    output: true
  krl:
    output: true
  olo:
    output: true
  orv:
    output: true
  mk:
    output: true
  gun:
    output: true
  am:
    output: true
  bxr:
    output: true
  hr:
    output: true
  hi:
    output: true
  id:
    output: true
  sme:
    output: true
  sr:
    output: true
  te:
    output: true
  th:
    output: true
  ur:
    output: true
  ug:
    output: true
  gd:
    output: true
  as:
    output: true
  mdf:
    output: true
  sms:
    output: true
  gsw:
    output: true
  quz:
    output: true
  koi:
    output: true
  qaf:
    output: true
  is:
    output: true
  mag:
    output: true
  sq:
    output: true
  abq:
    output: true
  sga:
    output: true
  ndg:
    output: true
  pgl:
    output: true
  mga:
    output: true
  oc:
    output: true
  ckt:
    output: true
  hit:
    output: true
  gv:
    output: true
  lzz:
    output: true
  ajp:
    output: true
  kfm:
    output: true
  nyq:
    output: true
  soj:
    output: true
  myu:
    output: true
  tpn:
    output: true
  aqz:
    output: true
  apu:
    output: true
  otk:
    output: true
  qtd:
    output: true
  naq:
    output: true
  cgg:
    output: true
  nyn:
    output: true
  pnt:
    output: true
  lad:
    output: true
  hil:
    output: true
  sw:
    output: true
  ess:
    output: true
  urb:
    output: true
  xnr:
    output: true
  gub:
    output: true
  si:
    output: true
  quc:
    output: true
  ojp:
    output: true
  qfn:
    output: true
  mpu:
    output: true
  lij:
    output: true
  nds:
    output: true
  bej:
    output: true
  ha:
    output: true
  hyw:
    output: true
  kab:
    output: true
  arr:
    output: true
  ne:
    output: true
  ti:
    output: true
# End of language collections (do not remove this comment, addlanguage.sh looks for it)



# Tagset conversion tables (even for languages that do not have their sections yet)
#
  tagset-conversion:
    output: true
    permalink: /tagset-conversion/:path.html
#
# Meeting materials
#
  v2_prelim:
    output: true
    permalink: /v2_prelim/:path.html
  v2:
    output: true
    permalink: /v2/:path.html
  misc:
    output: true
    permalink: /misc/:path.html


excerpt_separator: "\n\n"

# URL configuration

home: "http://universaldependencies.org/"
tracker: "https://github.com/universaldependencies/docs/issues"
git_raw: "https://raw.githubusercontent.com/universaldependencies/docs/pages-source"
git_edit: "https://github.com/universaldependencies/docs/edit/pages-source"
