source:       .
destination:  ./_site
markdown:     kramdown
# kramdown:
#   parse_block_html: true # allow markdown in <div> etc.
permalink:    date
# safe:         true
markdown_ext: md

# testing for redirect-from
baseurl: "/docs"

gems:
  - jekyll-redirect-from

collections:
#
# Universal
#
  u-pos:
    output: true
    permalink: /u/pos/:path.html
  u-feat:
    output: true
    permalink: /u/feat/:path.html
  u-dep:
    output: true
    permalink: /u/dep/:path.html
  u-overview:
    output: true
  ext-feat:
    output: true
    permalink: /u/ext-feat/:path.html
#
# English
#
  en-dep:
    output: true
    permalink: /en/dep/:path.html
  en-overview:
    output: true
#
# Finnish
#
  fi-dep:
    output: true
    permalink: /fi/dep/:path.html
  fi-overview:
    output: true
#
# Template
#
  template-pos:
    output: true
    permalink: /template/pos/:path.html
  template-feat:
    output: true
    permalink: /template/feat/:path.html
  template-dep:
    output: true
    permalink: /template/dep/:path.html
  template-overview:
    output: true

excerpt_separator: "\n\n"

# URL configuration

home: "http://universaldependencies.github.io/docs/"
tracker: "https://github.com/universaldependencies/docs/issues"
git_raw: "https://raw.githubusercontent.com/universaldependencies/docs/pages-source"
git_edit: "https://github.com/universaldependencies/docs/edit/pages-source"
